hunts:
  Simple:
    random-reward-commands: false
    reward-commands: [broadcast Testing %player%]
    require-species: true
    allow-legends: false
    allow-ultra-beasts: false
    allow-evolutions: true
    require-gender: false
    require-growth: false
    numer-of-possible-growths: 2
    require-nature: false
    number-of-possible-natures: 2
    require-iv-percentage: false
    random-iv-generation: true
    minimum-iv-percentage: 30
    maximum-iv-percentage: 100
    max-ivs: false
    iv-multiplier-enabled: false
    iv-multiplier: 1.5
    max-duration-minutes: 30
    timeoutBroadcast:
      - 'Hunt for %pokemon% timed out!
gui-height: 3
gui-name: PixelHunt
background-item: minecraft:stained_glass_pane
background-item-damage: 8
checkered-background: false
off-colour-background-item: minecraft:stained_glass_pane
off-colour-background-item-damage: 9
spawn-broadcast: []
